version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directories:
      - "/src/HomeKitDevice"
      - "/src/HomeKitHistory"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/src/docker-standalone"
    schedule:
      interval: "weekly"
    # Always increase the version requirement
    # to match the new version.
    versioning-strategy: increase
